[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[providers]
python = true
nodejs = false

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip", 
  "python311Packages.python-dotenv",
  "python311Packages.fastapi",
  "python311Packages.uvicorn",
  "python311Packages.openai",
  "python311Packages.requests", 
  "python311Packages.pydantic"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"