services:
  - type: web
    name: openai-astro-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python main.py
    healthCheckPath: /health
    envVars:
      - key: FORCE_REDEPLOY
        value: v2.3
      - key: PYTHON_VERSION
        value: 3.9.0